### ISSUE TITLE
チャレンジ問題について

### ISSUE THREAD

**Issue by oshima-yoppi** [typeshukatsu/20220611-event-questions#1]
初めまして。[問題３のチャレンジ問題]([20220611-event-questions](https://github.com/typeshukatsu/20220611-event-questions))のアルゴリズム説明について質問があります。
記載されているアルゴリズムの説明の場合、[7, 9, 8]のような配列を渡した場合、交換が発生せずソートできないのではないでしょうか？
ご返答お待ちしています。

**Comment by typeshukatsu** [comment]
ご質問ありがとうございます。

>[7, 9, 8]のような配列を渡した場合、交換が発生せずソートできないのではないでしょうか？

先頭が最小の場合には、例外的な処理をしてください。
よろしくお願いいたします。

**Comment by oshima-yoppi** [comment]
了解しました、ありがとうございます。
